### ISSUE TITLE
scan_for_themes() verfehlt seinen Zweck

### ISSUE THREAD

**Issue by aledjones** [si0nDE/riechtjonasgeradekomisch#13]
@DerAtrox Seit dem Einbinden der partiellen View für Scripte, wir das Feld für mehrere Themes immer angezeigt. Das ist mir beim nutzen der Oberfläche schon oft aufgefallen. Wir sollten mal den Einstiegspunkt von scandir() ändern :laughing: 

Zeile 51 in [/admin/index.php](https://github.com/si0nDE/riechtjonasgeradekomisch/blob/master/admin/index.php#L51)

**Comment by DerAtrox** [comment]
Kann dir da nicht ganz folgen. scan_for_themes() macht doch genau das, was es machen soll: Checken ob mehr als ein Theme existiert.

**Comment by aledjones** [comment]
Es wertet aber den Ordner auch als "Theme", da scandir() auch den Ordner als Eintrag im Array zurückgibt. Folglich ist der Theme-Switcher im Admin-Bereich immer eingeblendet, seit wir Subviews haben.

**Comment by DerAtrox** [comment]
fixed with a616bad2482ccd029ab6303bdbf40d1313a0a338
