### ISSUE TITLE
🍺

### ISSUE THREAD

**Issue by sebbo2002** [si0nDE/riechtjonasgeradekomisch#14]
`?format=🍺` -> 🙌🏼

**Comment by aledjones** [comment]
:beer: :heavy_check_mark:

-> [fcd1c1ba604ead27ecc1f9fd4fad438af4704678](https://github.com/si0nDE/riechtjonasgeradekomisch/tree/fcd1c1ba604ead27ecc1f9fd4fad438af4704678) :tada:
